# Load libraries

In [3]:
#Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statistics
import scipy.stats as st
import os

# Read configuration file

In [4]:
import yaml
 
try:
    with open("../config.yaml", "r") as file:
        config = yaml.safe_load(file)
except:
    print("Yaml configuration file not found!")

# Read data

In [5]:
df = pd.read_csv(config['output_data']['file'])
df = df.drop_duplicates()
df.head()

,Year,Experience_Level,Employment_Type,Position,Currency,Salary,Country,Remote_Amount,Company_Size
0,2025,Senior Level,Full-time,"Products, Research & Development",USD,170000,US,0,Medium
1,2025,Senior Level,Full-time,"Products, Research & Development",USD,110000,US,0,Medium
4,2025,Senior Level,Full-time,"Products, Research & Development",USD,143000,US,0,Medium
5,2025,Senior Level,Full-time,"Products, Research & Development",USD,106000,US,0,Medium
6,2025,Senior Level,Full-time,"Products, Research & Development",USD,360200,US,0,Medium

# Preparing file for the relational database

## Experience file

In [11]:
import pandas as pd

# Create the experience DataFrame
experience_df = pd.DataFrame({
    "experience_id": [i for i in range(1, df['Experience_Level'].nunique() + 1)],
    "name": df['Experience_Level'].unique()
})

# Trim spaces from all string columns in experience_df
experience_df = experience_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

# Display the cleaned DataFrame
display(experience_df)

# Save the cleaned DataFrame to CSV
experience_df.to_csv(config['output_data']['file1'], index=False)

/var/folders/2n/vdp8fcl915n4gbp1vcj_4vgw0000gp/T/ipykernel_59583/478301267.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  experience_df = experience_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

   experience_id             name
0              1     Senior Level
1              2        Mid Level
2              3      Entry Level
3              4  Executive Level

In [6]:
experience_df = pd.DataFrame({"experience_id": [ i for i in range(1, df['Experience_Level'].nunique() + 1)], "name": df['Experience_Level'].unique()})
display(experience_df)
experience_df.to_csv(config['output_data']['file1'], index=False)

   experience_id              name
0              1     Senior Level
1              2        Mid Level
2              3      Entry Level
3              4  Executive Level

## Currencies file

In [5]:
currency_df = pd.DataFrame({"currency_id": [ i for i in range(1, df['Currency'].nunique() + 1)], "name": df['Currency'].unique()})
display(currency_df)
currency_df.to_csv(config['output_data']['file2'], index=False)

   currency_id name
0            1  USD

## Company size file

In [6]:
company_size_df = pd.DataFrame({"size_id": [ i for i in range(1, df['Company_Size'].nunique() + 1)], "name": df['Company_Size'].unique()})
display(company_size_df)
company_size_df.to_csv(config['output_data']['file3'], index=False)

   size_id    name
0        1  Medium
1        2   Large
2        3   Small

## Employment type file

In [7]:
employment_type_df = pd.DataFrame({"employment_id": [ i for i in range(1, df['Employment_Type'].nunique() + 1)], "name": df['Employment_Type'].unique()})
display(employment_type_df)
employment_type_df .to_csv(config['output_data']['file4'], index=False)

   employment_id       name
0              1  Full-time
1              2  Part-time
2              3   Contract

## Remote File

In [8]:
remote_df = pd.DataFrame({"remote_id": [ i for i in range(1, df['Remote_Amount'].nunique() + 1)], "percentage": df['Remote_Amount'].unique()})
display(remote_df)
remote_df.to_csv(config['output_data']['file5'], index=False)

   remote_id  percentage
0          1           0
1          2         100
2          3          50

## Positions

In [9]:
positions_df = pd.DataFrame({"position_id": [ i for i in range(1, df['Position'].nunique() + 1)], "position": df['Position'].unique()})
display(positions_df)
positions_df.to_csv(config['output_data']['file6'], index=False)

   position_id                                    position
0            1            Products, Research & Development
1            2         Data Science, Engineers & Analytics
2            3                AI / ML Engineer / Developer
3            4                   AI / ML Software Engineer
4            5  AI / ML Sales, Consultant & Prof. Services
5            6                    AI / ML Computer Systems

## Countries

In [10]:
countries_df = pd.DataFrame({"country_id": [ i for i in range(1, df['Country'].nunique() + 1)], "name": df['Country'].unique()})
display(countries_df)
countries_df.to_csv(config['output_data']['file7'], index=False)

   country_id name
0           1   US

## Job id

In [11]:
job = df.copy()
job['job_id'] = [ i for i in range(1, job.shape[0]+1)]
job = job.iloc[:, [-1] + [i for i in range(job.shape[1]-1)]]
job.head()

,job_id,Year,Experience_Level,Employment_Type,Position,Currency,Salary,Country,Remote_Amount,Company_Size
0,1,2025,Senior Level,Full-time,"Products, Research & Development",USD,170000,US,0,Medium
1,2,2025,Senior Level,Full-time,"Products, Research & Development",USD,110000,US,0,Medium
4,3,2025,Senior Level,Full-time,"Products, Research & Development",USD,143000,US,0,Medium
5,4,2025,Senior Level,Full-time,"Products, Research & Development",USD,106000,US,0,Medium
6,5,2025,Senior Level,Full-time,"Products, Research & Development",USD,360200,US,0,Medium

# Combining tables

In [12]:
job = job.merge(remote_df, how="left", left_on="Remote_Amount", right_on="percentage")
job = job.loc[:, [col for col in job.columns if col not in ["Remote_Amount", "percentage"]]] 
job.head()

,job_id,Year,Experience_Level,Employment_Type,Position,Currency,Salary,Country,Company_Size,remote_id
0,1,2025,Senior Level,Full-time,"Products, Research & Development",USD,170000,US,Medium,1
1,2,2025,Senior Level,Full-time,"Products, Research & Development",USD,110000,US,Medium,1
2,3,2025,Senior Level,Full-time,"Products, Research & Development",USD,143000,US,Medium,1
3,4,2025,Senior Level,Full-time,"Products, Research & Development",USD,106000,US,Medium,1
4,5,2025,Senior Level,Full-time,"Products, Research & Development",USD,360200,US,Medium,1

In [13]:
job = job.merge(company_size_df, how="left", left_on="Company_Size", right_on="name")
job = job.loc[:, [col for col in job.columns if col not in ["Company_Size", "name"]]]
job.head()

,job_id,Year,Experience_Level,Employment_Type,Position,Currency,Salary,Country,remote_id,size_id
0,1,2025,Senior Level,Full-time,"Products, Research & Development",USD,170000,US,1,1
1,2,2025,Senior Level,Full-time,"Products, Research & Development",USD,110000,US,1,1
2,3,2025,Senior Level,Full-time,"Products, Research & Development",USD,143000,US,1,1
3,4,2025,Senior Level,Full-time,"Products, Research & Development",USD,106000,US,1,1
4,5,2025,Senior Level,Full-time,"Products, Research & Development",USD,360200,US,1,1

In [14]:
job = job.merge(currency_df, how="left", left_on="Currency", right_on="name")
job = job.loc[:, [col for col in job.columns if col not in ["Currency", "name"]]]
job.head()

,job_id,Year,Experience_Level,Employment_Type,Position,Salary,Country,remote_id,size_id,currency_id
0,1,2025,Senior Level,Full-time,"Products, Research & Development",170000,US,1,1,1
1,2,2025,Senior Level,Full-time,"Products, Research & Development",110000,US,1,1,1
2,3,2025,Senior Level,Full-time,"Products, Research & Development",143000,US,1,1,1
3,4,2025,Senior Level,Full-time,"Products, Research & Development",106000,US,1,1,1
4,5,2025,Senior Level,Full-time,"Products, Research & Development",360200,US,1,1,1

In [15]:
job = job.merge(experience_df, how="left", left_on="Experience_Level", right_on="name")
job = job.loc[:, [col for col in job.columns if col not in ["Experience_Level", "name"]]]
job.head()

,job_id,Year,Employment_Type,Position,Salary,Country,remote_id,size_id,currency_id,experience_id
0,1,2025,Full-time,"Products, Research & Development",170000,US,1,1,1,1
1,2,2025,Full-time,"Products, Research & Development",110000,US,1,1,1,1
2,3,2025,Full-time,"Products, Research & Development",143000,US,1,1,1,1
3,4,2025,Full-time,"Products, Research & Development",106000,US,1,1,1,1
4,5,2025,Full-time,"Products, Research & Development",360200,US,1,1,1,1

In [16]:
job = job.merge(employment_type_df, how="left", left_on="Employment_Type", right_on="name")
job = job.loc[:, [col for col in job.columns if col not in ["Employment_Type", "name"]]]
job.head()

,job_id,Year,Position,Salary,Country,remote_id,size_id,currency_id,experience_id,employment_id
0,1,2025,"Products, Research & Development",170000,US,1,1,1,1,1
1,2,2025,"Products, Research & Development",110000,US,1,1,1,1,1
2,3,2025,"Products, Research & Development",143000,US,1,1,1,1,1
3,4,2025,"Products, Research & Development",106000,US,1,1,1,1,1
4,5,2025,"Products, Research & Development",360200,US,1,1,1,1,1

In [17]:
job = job.merge(positions_df, how="left", left_on="Position", right_on="position")
job = job.loc[:, [col for col in job.columns if col not in ["Position", "position"]]]
job.head()

,job_id,Year,Salary,Country,remote_id,size_id,currency_id,experience_id,employment_id,position_id
0,1,2025,170000,US,1,1,1,1,1,1
1,2,2025,110000,US,1,1,1,1,1,1
2,3,2025,143000,US,1,1,1,1,1,1
3,4,2025,106000,US,1,1,1,1,1,1
4,5,2025,360200,US,1,1,1,1,1,1

In [18]:
countries_df.head()

   country_id name
0           1   US

In [19]:
job = job.merge(countries_df, how="left", left_on="Country", right_on="name")
job = job.loc[:, [col for col in job.columns if col not in ["Country", "name"]]]
job.head()

,job_id,Year,Salary,remote_id,size_id,currency_id,experience_id,employment_id,position_id,country_id
0,1,2025,170000,1,1,1,1,1,1,1
1,2,2025,110000,1,1,1,1,1,1,1
2,3,2025,143000,1,1,1,1,1,1,1
3,4,2025,106000,1,1,1,1,1,1,1
4,5,2025,360200,1,1,1,1,1,1,1

In [20]:
job.to_csv(config['output_data']['file10'], index=False)

In [21]:
job.shape

(19198, 10)